### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by Mushroomaner** [lancejames221b/shamirstego#1]
It seems something got wrong. When I try to run it, It show these ERROR for me ：

Traceback (most recent call last):
  File "ShamirStego.py", line 66, in <module>
    secret = stego_share_decrypt()
  File "ShamirStego.py", line 46, in stego_share_decrypt
    secret = bytes.fromhex(SecretSharer.recover_secret(shares))
  File "C:\Users\Thorn\.conda\envs\test_py3\lib\site-packages\secretsharing\sharing.py", line 110, in recover_secret
    points.append(share_string_to_point(share, cls.share_charset))
  File "C:\Users\Thorn\.conda\envs\test_py3\lib\site-packages\secretsharing\sharing.py", line 76, in share_string_to_point
    if not isinstance(share_string, str) and share_string.count('-') == 1:
AttributeError: 'NoneType' object has no attribute 'count'

I'm here to looking for your help. If I don't show my sincerity, that's because my English is not very good.

**Comment by Mushroomaner** [comment]
My pip package as list:

Package             Version
------------------- ---------
certifi             2020.6.20
colorama            0.4.5
crayons             0.3.0
cryptosteganography 0.8.3
exitstatus          1.4.0
hc-passphrase       1.2.1
piexif              1.1.3
Pillow              6.2.2
pip                 20.3.4
pycryptodomex       3.9.7
PySimpleGUI         4.60.4
secretsharing       0.2.6
setuptools          40.2.0
Stegano             0.9.7
utilitybelt         0.2.6
wheel               0.37.1
wincertstore        0.2

**Comment by Mushroomaner** [comment]
I use : 
WIN11 
python 3.5
